name: 'Go coverage report gha'
description: 'This action updates adds an HTML coverage report and SVG badge to your wiki'
branding:
  color: blue
  icon: award

runs:
  using: "composite"
  steps:
    - name: Get repository name
      shell: bash
      run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout wiki
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}.wiki
        path: ./.github/wiki/

    - name: Generate coverage report
      shell: bash
      env:
        REPO_NAME: ${{ env.REPOSITORY_NAME }}
      run: |
        ${{github.action_path}}/coverage.sh
        mv ${{github.action_path}}/coverage.svg ./.github/wiki/
        test ! -f ${{github.action_path}}/coverage.html || mv ${{github.action_path}}/coverage.html ./.github/wiki/
        cat ${{github.action_path}}/coverage.log >> ./.github/wiki/coverage.log
        sort -u -o ./.github/wiki/coverage.log ./.github/wiki/coverage.log

    - name: Push to wiki
      shell: bash
      run: |
        cd ./.github/wiki/
        git add --all
        git diff-index --quiet HEAD && exit
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git commit -m "Update coverage" && git push
